-- MariaDB

WITH R AS (
	SELECT NAME,
	ROUND((D_QTY/P_QTY)*100, 3) AS D_RATE
	FROM FACTORIES
	)
,R2 AS (
	SELECT
	NAME,
	GRADE,
	D_RATE,
	CASE WHEN GRADE >= 'D'
		THEN 'O'
		ELSE ''
		END
	FROM R JOIN GRADES G
	ON MIN_D_RATE <= D_RATE AND D_RATE < COALESCE(MAX_D_RATE, 1000)
)

SELECT * FROM R2
ORDER BY GRADE ASC,
	CASE WHEN GRADE >= 'D'
		THEN D_RATE END DESC,
	CASE WHEN GRADE < 'D'
		THEN D_RATE END ASC,
	NAME ASC;
